name: basic-reporting
version:: '2.0.0'
run-name: ${{ github.actor }} executed basic-reporting action
on: 
    schedule:
        - cron: '0 0 * * *' # Runs at midnight every day
    workflow_dispatch:
jobs:
    basic-reporting:
        runs-on: ubuntu-latest
        environment: MR4GH # Mediumroast for GitHub environment
        permissions:
          actions: read
          contents: write
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v3
            with:
              node-version: '20'
          - name: Install dependencies
            run: npm install
            working-directory: ./.github/actions/basic-reporting
          - name: Generate basic reports for companies and studies
            uses: ./.github/actions/basic-reporting
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
